### ISSUE TITLE
Should we disable High-Performance order storage?

### ISSUE THREAD

**Issue by GeoffCee** [woocommerce/woocommerce-legacy-rest-api#2]
When activating this plugin, WooCommerce issues a warning "This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated."

**Comment by Konamiman** [comment]
Hi, enabling HPOS is fine even when this plugin is installed. We disabled the incompatibility warning for it in WooCommerce 8.8: https://github.com/woocommerce/woocommerce/pull/45610

Indeed, the Legacy REST API itself is not compatible with HPOS. However this plugin is a special case as we are providing it for whoever needs to use other extensions or services that still depend on the Legacy REST API, thus the compatibility warning doesn't make much sense in this case.

I'm closing this issue but feel free to ask if you have more questions.
