### ISSUE TITLE
Security issues detected on my sites

### ISSUE THREAD

**Issue by Ania738** [woocommerce/woocommerce-legacy-rest-api#8]
Hi, 
I received an email today with the content: "Security issues detected on your site. We found outdated and/or compromised components in the following websites. Plugin: WooCommerce Legacy REST API." Please help me, what should I do?

![Screenshot 2024-03-21 182006](https://github.com/woocommerce/woocommerce-legacy-rest-api/assets/164440485/b45cba77-fcf3-4e87-b359-843d1e10b27d)

**Comment by barryhughes** [comment]
Closing:

- There is no particular security issue we are aware of.
- We did reach out to Hostinger about this, and this message apparently is most often used to indicate that the installed version of the plugin is not current.
- For further guidance, you should reach out to Hostinger directly.

https://wordpress.org/support/topic/security-issues-detected-on-your-site/
